var g;g||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,ca="object"==typeof process&&process.versions?.node&&"renderer"!=process.type,da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha="undefined"!=typeof document?document.currentScript?.src:void 0;"undefined"!=typeof __filename?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=g);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var ma=console.log.bind(console),h=console.error.bind(console),m,q=!1,na,la=a=>a.startsWith("file://"),oa,r,t,pa,qa,v,w,x,y,ra;
function sa(a){g.onAbort?.(a);a="Aborted("+a+")";h(a);q=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ta;async function ua(a){if(!m)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==ta&&m)a=new Uint8Array(m);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}
async function va(a,b){try{var c=await ua(a);return await WebAssembly.instantiate(c,b)}catch(d){h(`failed to asynchronously prepare wasm: ${d}`),sa(d)}}async function wa(a){var b=ta;if(!m&&!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){h(`wasm streaming compile failed: ${d}`),h("falling back to ArrayBuffer instantiation")}return va(b,a)}
class xa{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var ya=a=>{for(;0<a.length;)a.shift()(g)},za=[],Aa=[],Ba=()=>{var a=g.preRun.shift();Aa.push(a)},z=0,A=null,Ca=!0,Da=0,B={},Ea=a=>{a instanceof xa||"unwind"==a||fa(1,a)},Fa=a=>{na=a;Ca||0<Da||(g.onExit?.(a),q=!0);fa(a,new xa(a))},Ga=a=>{na=a;Fa(a)},Ha=()=>{if(!(Ca||0<Da))try{var a=na;na=a;Fa(a)}catch(b){Ea(b)}},Ia=a=>{if(!q)try{a(),Ha()}catch(b){Ea(b)}},Qa=(a,b)=>{Ja=a;Ka=b;if(C)if(La||=!0,0==a)F=function(){setTimeout(Ma,Math.max(0,Na+b-performance.now())|0)};else if(1==a)F=function(){Oa(Ma)};else if(2==
a){if("undefined"==typeof Pa)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Pa=d=>{c.push(d);if(ba){let e;(e=g).setImmediates??(e.setImmediates=[]);g.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}else Pa=setImmediate;F=function(){Pa(Ma)}}},Za=(a,b,c,d,e)=>{function k(){return f<Ra?(Ha(),!1):!0}C=a;Sa=d;var f=Ra;La=!1;Ma=function(){if(!q)if(0<
Ta.length){var l=Ta.shift();l.Id(l.wd);if(Ua){var n=Ua,p=0==n%1?n-1:Math.floor(n);Ua=l.zd?p:(8*n+(p+.5))/9}g.setStatus&&(l=g.statusMessage||"Please wait...",n=Ua??0,p=Va.Fd??0,n?n<p?g.setStatus("{message} ({expected - remaining}/{expected})"):g.setStatus(l):g.setStatus(""));k()&&setTimeout(Ma,0)}else if(k())if(Wa=Wa+1|0,1==Ja&&1<Ka&&0!=Wa%Ka)F();else{0==Ja&&(Na=performance.now());a:if(!q){for(l of Xa)if(!1===l())break a;Ia(a);for(n of Ya)n()}k()&&F()}};e||(0<b?Qa(0,1E3/b):Qa(1,1),F());if(c)throw"unwind";
},La=!1,F=null,Ra=0,C=null,Sa=0,Ja=0,Ka=0,Wa=0,Ta=[],Xa=[],Ya=[];function $a(){F=null;Ra++}var ab=0;function Oa(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===ab)ab=b+1E3/60;else for(;b+2>=ab;)ab+=1E3/60;setTimeout(a,Math.max(ab-b,0))}}
var Va={},Na,Ma,Pa,Ua,bb="undefined"!=typeof TextDecoder?new TextDecoder:void 0,G=(a,b=0,c)=>{var d=b;for(c=d+c;a[d]&&!(d>=c);)++d;if(16<d-b&&a.buffer&&bb)return bb.decode(a.subarray(b,d));for(c="";b<d;){var e=a[b++];if(e&128){var k=a[b++]&63;if(192==(e&224))c+=String.fromCharCode((e&31)<<6|k);else{var f=a[b++]&63;e=224==(e&240)?(e&15)<<12|k<<6|f:(e&7)<<18|k<<12|f<<6|a[b++]&63;65536>e?c+=String.fromCharCode(e):(e-=65536,c+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else c+=String.fromCharCode(e)}return c},
cb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],H=a=>{a=2<a?a?G(t,a):"":a;return cb[a]||("undefined"!=typeof document?document.querySelector(a):null)},db=a=>0>cb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},eb=[],fb,I=a=>{var b=eb[a];b||(eb[a]=b=fb.get(a));return b};function gb(a){var b=J.xc[a];b.target.removeEventListener(b.vc,b.ad,b.yc);J.xc.splice(a,1)}
function hb(){if(navigator.userActivation?navigator.userActivation.isActive:J.Oc&&J.qd.Lc){var a=J.Dc;J.Dc=[];for(var b of a)b.Rc(...b.Xc)}}function K(a){if(!a.target)return-4;if(a.zc)a.ad=function(c){++J.Oc;J.qd=a;hb();a.Ac(c);hb();--J.Oc},a.target.addEventListener(a.vc,a.ad,a.yc),J.xc.push(a);else for(var b=0;b<J.xc.length;++b)J.xc[b].target==a.target&&J.xc[b].vc==a.vc&&gb(b--);return 0}function ib(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var J={xd:0,Jd:0,Pc:0,Jc:0,Vc:0,Tc:0,Mc:0,Dd:0,Od:0,Cd:0,Nc:0,Qc:0,Xd:0,Sc:0,Ld(a,b,c){r.set(r.subarray(b,b+c),a)},Qd(){for(;J.xc.length;)gb(J.xc.length-1);J.Dc=[]},Oc:0,Dc:[],Bd(a,b,c){function d(k,f){if(k.length!=f.length)return!1;for(var l in k)if(k[l]!=f[l])return!1;return!0}for(var e of J.Dc)if(e.Rc==a&&d(e.Xc,c))return;J.Dc.push({Rc:a,ed:b,Xc:c});J.Dc.sort((k,f)=>k.ed<f.ed)},Sd(a){J.Dc=J.Dc.filter(b=>b.Rc!=a)},xc:[],Rd:(a,b)=>{for(var c=0;c<J.xc.length;++c)J.xc[c].target!=a||b&&b!=J.xc[c].vc||
gb(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},L=(a,b,c)=>{var d=t;if(!(0<c))return 0;var e=b;c=b+c-1;for(var k=0;k<a.length;++k){var f=a.codePointAt(k);if(127>=f){if(b>=c)break;d[b++]=f}else if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>6;d[b++]=128|f&63}else if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12;d[b++]=128|f>>6&63;d[b++]=128|f&63}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&63;d[b++]=128|f>>6&63;d[b++]=128|f&63;k++}}d[b]=0;return b-
e},jb=(a,b,c,d,e,k)=>{J.Mc||(J.Mc=M(256));a={target:H(a),vc:k,zc:d,Ac:(f=event)=>{var l=f.target.id?f.target.id:"",n=J.Mc;L(ib(f.target),n+0,128);L(l,n+128,128);I(d)(e,n,b)&&f.preventDefault()},yc:c};return K(a)},kb=(a,b,c,d,e)=>{J.Nc||(J.Nc=M(276));return K({target:a,vc:e,zc:d,Ac:(k=event)=>{var f=J.Nc,l=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement||document.msFullscreenElement,n=!!l;r[f]=n;r[f+1]=J.fullscreenEnabled();
var p=n?l:J.ud,u=p?.id||"";L(ib(p),f+2,128);L(u,f+130,128);v[f+260>>2]=p?p.clientWidth:0;v[f+264>>2]=p?p.clientHeight:0;v[f+268>>2]=screen.width;v[f+272>>2]=screen.height;n&&(J.ud=l);I(d)(19,f,b)&&k.preventDefault()},yc:c})},lb=(a,b,c,d,e,k)=>{J.Pc||(J.Pc=M(160));a={target:H(a),vc:k,zc:d,Ac:f=>{var l=J.Pc;y[l>>3]=f.timeStamp;var n=l>>2;v[n+2]=f.location;r[l+12]=f.ctrlKey;r[l+13]=f.shiftKey;r[l+14]=f.altKey;r[l+15]=f.metaKey;r[l+16]=f.repeat;v[n+5]=f.charCode;v[n+6]=f.keyCode;v[n+7]=f.which;L(f.key||
"",l+32,32);L(f.code||"",l+64,32);L(f.char||"",l+96,32);L(f.locale||"",l+128,32);I(d)(e,l,b)&&f.preventDefault()},yc:c};return K(a)},mb=(a,b,c)=>{y[a>>3]=b.timeStamp;var d=a>>2;v[d+2]=b.screenX;v[d+3]=b.screenY;v[d+4]=b.clientX;v[d+5]=b.clientY;r[a+24]=b.ctrlKey;r[a+25]=b.shiftKey;r[a+26]=b.altKey;r[a+27]=b.metaKey;pa[2*d+14]=b.button;pa[2*d+15]=b.buttons;v[d+8]=b.movementX;v[d+9]=b.movementY;a=db(c);v[d+10]=b.clientX-(a.left|0);v[d+11]=b.clientY-(a.top|0)},nb=(a,b,c,d,e,k)=>{J.Jc||(J.Jc=M(64));a=
H(a);return K({target:a,Lc:"mousemove"!=k&&"mouseenter"!=k&&"mouseleave"!=k,vc:k,zc:d,Ac:(f=event)=>{mb(J.Jc,f,a);I(d)(e,J.Jc,b)&&f.preventDefault()},yc:c})},ob=(a,b,c,d)=>{J.Qc||(J.Qc=M(257));return K({target:a,vc:"pointerlockchange",zc:d,Ac:(e=event)=>{var k=J.Qc,f=document.pointerLockElement;r[k]=!!f;var l=f?.id||"";L(ib(f),k+1,128);L(l,k+129,128);I(d)(20,k,b)&&e.preventDefault()},yc:c})},pb=(a,b,c,d)=>K({target:a,vc:"pointerlockerror",zc:d,Ac:(e=event)=>{I(d)(38,0,b)&&e.preventDefault()},yc:c}),
qb=(a,b,c,d)=>{J.Tc||(J.Tc=M(36));a=H(a);return K({target:a,vc:"resize",zc:d,Ac:(e=event)=>{if(e.target==a){var k=document.body;if(k){var f=J.Tc;v[f>>2]=0;v[f+4>>2]=k.clientWidth;v[f+8>>2]=k.clientHeight;v[f+12>>2]=innerWidth;v[f+16>>2]=innerHeight;v[f+20>>2]=outerWidth;v[f+24>>2]=outerHeight;v[f+28>>2]=pageXOffset|0;v[f+32>>2]=pageYOffset|0;I(d)(10,f,b)&&e.preventDefault()}}},yc:c})},rb=(a,b,c,d,e,k)=>{J.Sc||(J.Sc=M(1552));a=H(a);return K({target:a,Lc:"touchstart"==k||"touchend"==k,vc:k,zc:d,Ac:f=>
{var l={},n=f.touches;for(var p of n)p.bd=p.dd=0,l[p.identifier]=p;for(var u of f.changedTouches)u.bd=1,l[u.identifier]=u;for(var D of f.targetTouches)l[D.identifier].dd=1;n=J.Sc;y[n>>3]=f.timeStamp;r[n+12]=f.ctrlKey;r[n+13]=f.shiftKey;r[n+14]=f.altKey;r[n+15]=f.metaKey;p=n+16;u=db(a);D=0;for(let E of Object.values(l))if(l=p>>2,v[l]=E.identifier,v[l+1]=E.screenX,v[l+2]=E.screenY,v[l+3]=E.clientX,v[l+4]=E.clientY,v[l+5]=E.pageX,v[l+6]=E.pageY,r[p+28]=E.bd,r[p+29]=E.dd,v[l+8]=E.clientX-(u.left|0),v[l+
9]=E.clientY-(u.top|0),p+=48,31<++D)break;v[n+8>>2]=D;I(d)(e,n,b)&&f.preventDefault()},yc:c})},N,sb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,k)=>b.drawArraysInstancedANGLE(c,d,e,k),a.drawElementsInstanced=(c,d,e,k,f)=>b.drawElementsInstancedANGLE(c,d,e,k,f))},tb=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),
a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},ub=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},vb=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},wb=1,O=[],P=[],xb=[],yb=[],Q=[],R=[],zb=[],Ab=[],S=[],Bb={},Cb=4,Db=0,Eb=a=>{for(var b=wb++,c=a.length;c<b;c++)a[c]=null;return b},U=(a,b,c,d)=>{for(var e=0;e<a;e++){var k=N[c](),f=k&&Eb(d);k?(k.name=f,d[f]=k):T||=1282;v[b+4*e>>2]=f}},Gb=(a,b)=>{a.pd||(a.pd=a.getContext,a.getContext=function(d,e){e=a.pd(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.cd?a.getContext("webgl2",b):a.getContext("webgl",b);return c?
Fb(c,b):0},Fb=(a,b)=>{var c=Eb(Ab),d={handle:c,attributes:b,version:b.cd,Wc:a};a.canvas&&(a.canvas.vd=d);Ab[c]=d;("undefined"==typeof b.$c||b.$c)&&Hb(d);return c},Hb=a=>{a||=V;if(!a.td){a.td=!0;var b=a.Wc;b.Nd=b.getExtension("WEBGL_multi_draw");b.Hd=b.getExtension("EXT_polygon_offset_clamp");b.Gd=b.getExtension("EXT_clip_control");b.Yd=b.getExtension("WEBGL_polygon_mode");sb(b);tb(b);ub(b);b.Ed=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.Kd=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");
2<=a.version&&(b.Zc=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.Zc)b.Zc=b.getExtension("EXT_disjoint_timer_query");vb(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},T,V,Ib=(a,b,c,d,e,k)=>{a={target:H(a),vc:k,zc:d,Ac:(f=event)=>{I(d)(e,0,b)&&f.preventDefault()},yc:c};K(a)},Jb=(a,b,c,d)=>{J.Vc||(J.Vc=M(96));return K({target:a,Lc:!0,vc:"wheel",zc:d,Ac:(e=event)=>{var k=J.Vc;mb(k,e,a);y[k+64>>3]=e.deltaX;y[k+72>>3]=e.deltaY;y[k+80>>3]=e.deltaZ;
v[k+88>>2]=e.deltaMode;I(d)(9,k,b)&&e.preventDefault()},yc:c})},Kb=["default","low-power","high-performance"],Lb=[null,[],[]],Mb=[],Nb=()=>{var a=vb(N);return a=a.concat(a.map(b=>"GL_"+b))},Ob=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=N.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>V.version){T||=1282;return}c=Nb().length;break;case 33307:case 33308:if(2>V.version){T||=1280;return}c=33307==a?3:0}if(void 0===
c)switch(d=N.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":T||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=0;break;default:T||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=
0;a<d.length;++a)v[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){T||=1280;h(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:T||=1280;h(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}v[b>>2]=c}else T||=1281},Pb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Qb=a=>{var b=Pb(a)+
1,c=M(b);c&&L(a,c,b);return c},Rb=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Sb=a=>{a-=5120;return 0==a?r:1==a?t:2==a?pa:4==a?v:6==a?x:5==a||28922==a||28520==a||30779==a||30782==a?w:qa},W=a=>{var b=N.rd;if(b){var c=b.Fc[a];"number"==typeof c&&(b.Fc[a]=c=N.getUniformLocation(b,b.nd[a]+(0<c?`[${c}]`:"")));return c}T||=1282},X=[],Tb=[],Vb=a=>{var b=Pb(a)+1,c=Ub(b);L(a,c,b);return c},Yb=a=>{var b=Wb();a();Xb(b)};g.requestAnimationFrame=Oa;g.pauseMainLoop=$a;
g.resumeMainLoop=function(){Ra++;var a=Ja,b=Ka,c=C;C=null;Za(c,0,!1,Sa,!0);Qa(a,b);F()};g.preMainLoop&&Xa.push(g.preMainLoop);g.postMainLoop&&Ya.push(g.postMainLoop);for(let a=0;32>a;++a)Mb.push(Array(a));for(var Zb=new Float32Array(288),Y=0;288>=Y;++Y)X[Y]=Zb.subarray(0,Y);var $b=new Int32Array(288);for(Y=0;288>=Y;++Y)Tb[Y]=$b.subarray(0,Y);g.noExitRuntime&&(Ca=g.noExitRuntime);g.print&&(ma=g.print);g.printErr&&(h=g.printErr);g.wasmBinary&&(m=g.wasmBinary);g.arguments&&(da=g.arguments);
g.thisProgram&&(ea=g.thisProgram);if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.shift()();
var ac,bc,cc,dc,ec,fc,gc,hc,ic,jc,kc,lc,mc,nc,M,Xb,Ub,Wb,oc={mb:()=>{},_a:()=>sa(""),gb:()=>{Ca=!1;Da=0},hb:(a,b)=>{B[a]&&(clearTimeout(B[a].id),delete B[a]);if(!b)return 0;var c=setTimeout(()=>{delete B[a];Ia(()=>nc(a,performance.now()))},b);B[a]={id:c,Wd:b};return 0},_b:function(a,b,c){if(!(0<=a&&3>=a))return 28;ra[c>>3]=BigInt(Math.round(1E6*(0===a?Date.now():performance.now())));return 0},lb:function(a,b,c){a=a?G(t,a):"";console.log("load file: ",a);a=window.localStorage.getItem(a);if(!a)return 0;
a=atob(a);if(a.length>c)return 0;for(c=0;c<a.length;c++)t[b+c]=a.charCodeAt(c);return a.length},nb:function(a,b,c){a=a?G(t,a):"";console.log("save file: ",a);b=t.subarray(b,b+c);console.log("save file bytes len: ",c);c=btoa(String.fromCharCode(...b));window.localStorage.setItem(a,c)},Ta:()=>{$a();C=null},G:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,L:(a,b,c)=>{a=H(a);if(!a)return-4;a=db(a);y[b>>3]=a.width;y[c>>3]=a.height;return 0},Ua:()=>performance.now(),$a:(a,b)=>{function c(d){I(a)(d,
b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},Zb:()=>{sa("OOM")},P:(a,b,c,d)=>jb(a,b,c,d,12,"blur"),D:(a,b,c)=>{a=H(a);if(!a)return-4;a.width=b;a.height=c;return 0},Q:(a,b,c,d)=>jb(a,b,c,d,13,"focus"),O:(a,b,c,d)=>{if(!J.fullscreenEnabled())return-1;a=H(a);if(!a)return-4;kb(a,b,c,d,"webkitfullscreenchange");return kb(a,b,c,d,"fullscreenchange")},_:(a,b,c,d)=>lb(a,b,c,d,2,"keydown"),Y:(a,b,c,d)=>lb(a,b,c,d,1,"keypress"),Z:(a,b,c,d)=>lb(a,b,c,d,3,"keyup"),ab:(a,b,c)=>{a=I(a);Za(a,b,
c)},ka:(a,b,c,d)=>nb(a,b,c,d,5,"mousedown"),fa:(a,b,c,d)=>nb(a,b,c,d,33,"mouseenter"),ca:(a,b,c,d)=>nb(a,b,c,d,34,"mouseleave"),ha:(a,b,c,d)=>nb(a,b,c,d,8,"mousemove"),ia:(a,b,c,d)=>nb(a,b,c,d,6,"mouseup"),S:(a,b,c,d)=>document.body?.requestPointerLock?(a=H(a))?ob(a,b,c,d):-4:-1,R:(a,b,c,d)=>document.body?.requestPointerLock?(a=H(a))?pb(a,b,c,d):-4:-1,J:(a,b,c,d)=>qb(a,b,c,d),T:(a,b,c,d)=>rb(a,b,c,d,25,"touchcancel"),U:(a,b,c,d)=>rb(a,b,c,d,23,"touchend"),V:(a,b,c,d)=>rb(a,b,c,d,24,"touchmove"),W:(a,
b,c,d)=>rb(a,b,c,d,22,"touchstart"),N:(a,b,c,d)=>{Ib(a,b,c,d,31,"webglcontextlost");return 0},M:(a,b,c,d)=>{Ib(a,b,c,d,32,"webglcontextrestored");return 0},$:(a,b,c,d)=>(a=H(a))?"undefined"!=typeof a.onwheel?Jb(a,b,c,d):-1:-4,ya:(a,b)=>{var c=b>>2;b={alpha:!!r[b+0],depth:!!r[b+1],stencil:!!r[b+2],antialias:!!r[b+3],premultipliedAlpha:!!r[b+4],preserveDrawingBuffer:!!r[b+5],powerPreference:Kb[v[c+2]],failIfMajorPerformanceCaveat:!!r[b+12],cd:v[c+4],Md:v[c+5],$c:r[b+24],sd:r[b+25],Pd:v[c+7],Td:r[b+
32]};a=H(a);return!a||b.sd?0:Gb(a,b)},ua:a=>{V=Ab[a];g.ctx=N=V?.Wc;return!a||N?0:-5},ib:function(){return 52},jb:()=>52,kb:function(){return 70},X:(a,b,c,d)=>{for(var e=0,k=0;k<c;k++){var f=w[b>>2],l=w[b+4>>2];b+=8;for(var n=0;n<l;n++){var p=a,u=t[f+n],D=Lb[p];0===u||10===u?((1===p?ma:h)(G(D)),D.length=0):D.push(u)}e+=l}w[d>>2]=e;return 0},s:a=>N.activeTexture(a),o:(a,b)=>{N.attachShader(P[a],R[b])},b:(a,b)=>{35051==a?N.Yc=b:35052==a&&(N.Ec=b);N.bindBuffer(a,O[b])},ga:(a,b,c)=>{N.bindBufferBase(a,
b,O[c])},Yb:(a,b,c,d,e)=>{N.bindBufferRange(a,b,O[c],d,e)},f:(a,b)=>{N.bindFramebuffer(a,xb[b])},wa:(a,b)=>{N.bindRenderbuffer(a,yb[b])},r:(a,b)=>{N.bindSampler(a,S[b])},g:(a,b)=>{N.bindTexture(a,Q[b])},I:a=>{N.bindVertexArray(zb[a])},na:(a,b,c,d)=>N.blendColor(a,b,c,d),oa:(a,b)=>N.blendEquationSeparate(a,b),pa:(a,b,c,d)=>N.blendFuncSeparate(a,b,c,d),Fb:(a,b,c,d,e,k,f,l,n,p)=>N.blitFramebuffer(a,b,c,d,e,k,f,l,n,p),Ha:(a,b,c,d)=>{2<=V.version?c&&b?N.bufferData(a,t,d,c,b):N.bufferData(a,b,d):N.bufferData(a,
c?t.subarray(c,c+b):b,d)},E:(a,b,c,d)=>{2<=V.version?c&&N.bufferSubData(a,b,t,d,c):N.bufferSubData(a,b,t.subarray(d,d+c))},rb:a=>N.checkFramebufferStatus(a),ta:(a,b,c,d)=>N.clearBufferfi(a,b,c,d),u:(a,b,c)=>{N.clearBufferfv(a,b,x,c>>2)},sa:(a,b,c)=>{N.clearBufferiv(a,b,v,c>>2)},h:(a,b,c,d)=>{N.colorMask(!!a,!!b,!!c,!!d)},ub:a=>{N.compileShader(R[a])},Ab:(a,b,c,d,e,k,f,l,n)=>{2<=V.version?N.Ec||!l?N.compressedTexSubImage2D(a,b,c,d,e,k,f,l,n):N.compressedTexSubImage2D(a,b,c,d,e,k,f,t,n,l):N.compressedTexSubImage2D(a,
b,c,d,e,k,f,t.subarray(n,n+l))},yb:(a,b,c,d,e,k,f,l,n,p,u)=>{N.Ec?N.compressedTexSubImage3D(a,b,c,d,e,k,f,l,n,p,u):N.compressedTexSubImage3D(a,b,c,d,e,k,f,l,n,t,u,p)},Ca:()=>{var a=Eb(P),b=N.createProgram();b.name=a;b.Ic=b.Gc=b.Hc=0;b.Uc=1;P[a]=b;return a},wb:a=>{var b=Eb(R);R[b]=N.createShader(a);return b},ma:a=>N.cullFace(a),Bb:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=O[d];e&&(N.deleteBuffer(e),e.name=0,O[d]=null,d==N.Yc&&(N.Yc=0),d==N.Ec&&(N.Ec=0))}},F:(a,b)=>{for(var c=0;c<a;++c){var d=
v[b+4*c>>2],e=xb[d];e&&(N.deleteFramebuffer(e),e.name=0,xb[d]=null)}},k:a=>{if(a){var b=P[a];b?(N.deleteProgram(b),b.name=0,P[a]=null):T||=1281}},Ka:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=yb[d];e&&(N.deleteRenderbuffer(e),e.name=0,yb[d]=null)}},La:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=S[d];e&&(N.deleteSampler(e),e.name=0,S[d]=null)}},i:a=>{if(a){var b=R[a];b?(N.deleteShader(b),R[a]=null):T||=1281}},p:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2],e=Q[d];e&&(N.deleteTexture(e),
e.name=0,Q[d]=null)}},Ja:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+4*c>>2];N.deleteVertexArray(zb[d]);zb[d]=null}},m:a=>N.depthFunc(a),n:a=>{N.depthMask(!!a)},c:a=>N.disable(a),ja:a=>{N.disableVertexAttribArray(a)},Hb:(a,b,c)=>{N.drawArrays(a,b,c)},Ib:(a,b,c,d)=>{N.drawArraysInstanced(a,b,c,d)},y:(a,b)=>{for(var c=Mb[a],d=0;d<a;d++)c[d]=v[b+4*d>>2];N.drawBuffers(c)},Jb:(a,b,c,d)=>{N.drawElements(a,b,c,d)},Kb:(a,b,c,d,e)=>{N.drawElementsInstanced(a,b,c,d,e)},e:a=>N.enable(a),Ub:a=>{N.enableVertexAttribArray(a)},
x:(a,b,c,d)=>{N.framebufferRenderbuffer(a,b,c,yb[d])},da:(a,b,c,d,e)=>{N.framebufferTexture2D(a,b,c,Q[d],e)},sb:(a,b,c,d,e)=>{N.framebufferTextureLayer(a,b,Q[c],d,e)},la:a=>N.frontFace(a),Ia:(a,b)=>{U(a,b,"createBuffer",O)},H:(a,b)=>{U(a,b,"createFramebuffer",xb)},xa:(a,b)=>{U(a,b,"createRenderbuffer",yb)},Da:(a,b)=>{U(a,b,"createSampler",S)},Ga:(a,b)=>{U(a,b,"createTexture",Q)},Na:(a,b)=>{U(a,b,"createVertexArray",zb)},za:(a,b)=>N.getAttribLocation(P[a],b?G(t,b):""),a:(a,b)=>Ob(a,b),Ba:(a,b,c,d)=>
{a=N.getProgramInfoLog(P[a]);null===a&&(a="(unknown error)");b=0<b&&d?L(a,d,b):0;c&&(v[c>>2]=b)},A:(a,b,c)=>{if(c)if(a>=wb)T||=1281;else if(a=P[a],35716==b)a=N.getProgramInfoLog(a),null===a&&(a="(unknown error)"),v[c>>2]=a.length+1;else if(35719==b){if(!a.Ic){var d=N.getProgramParameter(a,35718);for(b=0;b<d;++b)a.Ic=Math.max(a.Ic,N.getActiveUniform(a,b).name.length+1)}v[c>>2]=a.Ic}else if(35722==b){if(!a.Gc)for(d=N.getProgramParameter(a,35721),b=0;b<d;++b)a.Gc=Math.max(a.Gc,N.getActiveAttrib(a,b).name.length+
1);v[c>>2]=a.Gc}else if(35381==b){if(!a.Hc)for(d=N.getProgramParameter(a,35382),b=0;b<d;++b)a.Hc=Math.max(a.Hc,N.getActiveUniformBlockName(a,b).length+1);v[c>>2]=a.Hc}else v[c>>2]=N.getProgramParameter(a,b);else T||=1281},tb:(a,b,c,d)=>{a=N.getShaderInfoLog(R[a]);null===a&&(a="(unknown error)");b=0<b&&d?L(a,d,b):0;c&&(v[c>>2]=b)},ea:(a,b,c)=>{c?35716==b?(a=N.getShaderInfoLog(R[a]),null===a&&(a="(unknown error)"),v[c>>2]=a?a.length+1:0):35720==b?(a=N.getShaderSource(R[a]),v[c>>2]=a?a.length+1:0):v[c>>
2]=N.getShaderParameter(R[a],b):T||=1281},Oa:(a,b)=>{if(2>V.version)return T||=1282,0;var c=Bb[a];if(c)return 0>b||b>=c.length?(T||=1281,0):c[b];switch(a){case 7939:return c=Nb().map(Qb),c=Bb[a]=c,0>b||b>=c.length?(T||=1281,0):c[b];default:return T||=1280,0}},z:(a,b)=>{b=b?G(t,b):"";if(a=P[a]){var c=a,d=c.Fc,e=c.od,k;if(!d){c.Fc=d={};c.nd={};var f=N.getProgramParameter(c,35718);for(k=0;k<f;++k){var l=N.getActiveUniform(c,k);var n=l.name;l=l.size;var p=Rb(n);p=0<p?n.slice(0,p):n;var u=c.Uc;c.Uc+=l;
e[p]=[l,u];for(n=0;n<l;++n)d[u]=n,c.nd[u++]=p}}c=a.Fc;d=0;e=b;k=Rb(b);0<k&&(d=parseInt(b.slice(k+1))>>>0,e=b.slice(0,k));if((e=a.od[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||N.getUniformLocation(a,b)))return d}else T||=1281;return-1},Eb:(a,b,c)=>{for(var d=Mb[b],e=0;e<b;e++)d[e]=v[c+4*e>>2];N.invalidateFramebuffer(a,d)},B:a=>{a=P[a];N.linkProgram(a);a.Fc=0;a.od={}},Ma:(a,b)=>{3317==a?Cb=b:3314==a&&(Db=b);N.pixelStorei(a,b)},t:(a,b)=>N.polygonOffset(a,b),Gb:a=>N.readBuffer(a),va:(a,b,c,d,e)=>N.renderbufferStorageMultisample(a,
b,c,d,e),C:(a,b,c)=>{N.samplerParameterf(S[a],b,c)},d:(a,b,c)=>{N.samplerParameteri(S[a],b,c)},v:(a,b,c,d)=>N.scissor(a,b,c,d),vb:(a,b,c,d)=>{for(var e="",k=0;k<b;++k){var f=(f=w[c+4*k>>2])?G(t,f,d?w[d+4*k>>2]:void 0):"";e+=f}N.shaderSource(R[a],e)},Db:(a,b,c)=>N.stencilFunc(a,b,c),ra:(a,b,c,d)=>N.stencilFuncSeparate(a,b,c,d),j:a=>N.stencilMask(a),Cb:(a,b,c)=>N.stencilOp(a,b,c),qa:(a,b,c,d)=>N.stencilOpSeparate(a,b,c,d),Fa:(a,b,c,d,e)=>N.texStorage2D(a,b,c,d,e),Ea:(a,b,c,d,e,k)=>N.texStorage3D(a,
b,c,d,e,k),zb:(a,b,c,d,e,k,f,l,n)=>{if(2<=V.version){if(N.Ec){N.texSubImage2D(a,b,c,d,e,k,f,l,n);return}if(n){var p=Sb(l);N.texSubImage2D(a,b,c,d,e,k,f,l,p,n>>>31-Math.clz32(p.BYTES_PER_ELEMENT));return}}if(n){p=Sb(l);var u=k*((Db||e)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[f-6402]||1)*p.BYTES_PER_ELEMENT+Cb-1&-Cb);n=p.subarray(n>>>31-Math.clz32(p.BYTES_PER_ELEMENT),n+u>>>31-Math.clz32(p.BYTES_PER_ELEMENT))}else n=null;N.texSubImage2D(a,b,c,d,e,k,f,l,n)},xb:(a,b,c,d,e,k,f,l,
n,p,u)=>{if(N.Ec)N.texSubImage3D(a,b,c,d,e,k,f,l,n,p,u);else if(u){var D=Sb(p);N.texSubImage3D(a,b,c,d,e,k,f,l,n,p,D,u>>>31-Math.clz32(D.BYTES_PER_ELEMENT))}else N.texSubImage3D(a,b,c,d,e,k,f,l,n,p,null)},Tb:(a,b,c)=>{if(2<=V.version)b&&N.uniform1fv(W(a),x,c>>2,b);else{if(288>=b)for(var d=X[b],e=0;e<b;++e)d[e]=x[c+4*e>>2];else d=x.subarray(c>>2,c+4*b>>2);N.uniform1fv(W(a),d)}},Aa:(a,b)=>{N.uniform1i(W(a),b)},Pb:(a,b,c)=>{if(2<=V.version)b&&N.uniform1iv(W(a),v,c>>2,b);else{if(288>=b)for(var d=Tb[b],
e=0;e<b;++e)d[e]=v[c+4*e>>2];else d=v.subarray(c>>2,c+4*b>>2);N.uniform1iv(W(a),d)}},Sb:(a,b,c)=>{if(2<=V.version)b&&N.uniform2fv(W(a),x,c>>2,2*b);else{if(144>=b){b*=2;for(var d=X[b],e=0;e<b;e+=2)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2]}else d=x.subarray(c>>2,c+8*b>>2);N.uniform2fv(W(a),d)}},Ob:(a,b,c)=>{if(2<=V.version)b&&N.uniform2iv(W(a),v,c>>2,2*b);else{if(144>=b){b*=2;for(var d=Tb[b],e=0;e<b;e+=2)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2]}else d=v.subarray(c>>2,c+8*b>>2);N.uniform2iv(W(a),d)}},Rb:(a,
b,c)=>{if(2<=V.version)b&&N.uniform3fv(W(a),x,c>>2,3*b);else{if(96>=b){b*=3;for(var d=X[b],e=0;e<b;e+=3)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2]}else d=x.subarray(c>>2,c+12*b>>2);N.uniform3fv(W(a),d)}},Nb:(a,b,c)=>{if(2<=V.version)b&&N.uniform3iv(W(a),v,c>>2,3*b);else{if(96>=b){b*=3;for(var d=Tb[b],e=0;e<b;e+=3)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2]}else d=v.subarray(c>>2,c+12*b>>2);N.uniform3iv(W(a),d)}},Qb:(a,b,c)=>{if(2<=V.version)b&&N.uniform4fv(W(a),
x,c>>2,4*b);else{if(72>=b){var d=X[4*b],e=x;c>>=2;b*=4;for(var k=0;k<b;k+=4){var f=c+k;d[k]=e[f];d[k+1]=e[f+1];d[k+2]=e[f+2];d[k+3]=e[f+3]}}else d=x.subarray(c>>2,c+16*b>>2);N.uniform4fv(W(a),d)}},Mb:(a,b,c)=>{if(2<=V.version)b&&N.uniform4iv(W(a),v,c>>2,4*b);else{if(72>=b){b*=4;for(var d=Tb[b],e=0;e<b;e+=4)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2],d[e+3]=v[c+(4*e+12)>>2]}else d=v.subarray(c>>2,c+16*b>>2);N.uniform4iv(W(a),d)}},Lb:(a,b,c,d)=>{if(2<=V.version)b&&N.uniformMatrix4fv(W(a),
!!c,x,d>>2,16*b);else{if(18>=b){var e=X[16*b],k=x;d>>=2;b*=16;for(var f=0;f<b;f+=16){var l=d+f;e[f]=k[l];e[f+1]=k[l+1];e[f+2]=k[l+2];e[f+3]=k[l+3];e[f+4]=k[l+4];e[f+5]=k[l+5];e[f+6]=k[l+6];e[f+7]=k[l+7];e[f+8]=k[l+8];e[f+9]=k[l+9];e[f+10]=k[l+10];e[f+11]=k[l+11];e[f+12]=k[l+12];e[f+13]=k[l+13];e[f+14]=k[l+14];e[f+15]=k[l+15]}}else e=x.subarray(d>>2,d+64*b>>2);N.uniformMatrix4fv(W(a),!!c,e)}},l:a=>{a=P[a];N.useProgram(a);N.rd=a},Vb:(a,b)=>{N.vertexAttribDivisor(a,b)},Wb:(a,b,c,d,e)=>{N.vertexAttribIPointer(a,
b,c,d,e)},Xb:(a,b,c,d,e,k)=>{N.vertexAttribPointer(a,b,c,!!d,e,k)},w:(a,b,c,d)=>N.viewport(a,b,c,d),fb:Fa,eb:function(){g.gd=a=>{0!=cc()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",g.gd)},cb:function(){g.md=a=>{const b=a.clipboardData.getData("text");Yb(()=>{const c=Vb(b);bc(c)})};window.addEventListener("paste",g.md)},bb:function(){g.Ud=[];g.hd=b=>{b.stopPropagation();b.preventDefault()};g.jd=b=>{b.stopPropagation();b.preventDefault()};g.kd=b=>{b.stopPropagation();
b.preventDefault()};g.ld=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;g.Vd=c;dc(c.length);for(let e=0;e<c.length;e++)Yb(()=>{const k=Vb(c[e].name);ec(e,k)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);fc(b.clientX,b.clientY,d)};const a=g.Bc;a.addEventListener("dragenter",g.hd,!1);a.addEventListener("dragleave",g.jd,!1);a.addEventListener("dragover",g.kd,!1);a.addEventListener("drop",g.ld,!1)},Wa:function(){const a=document.getElementById("sokol-app-favicon");
a&&document.head.removeChild(a)},Xa:function(a){g.Kc&&(URL.revokeObjectURL(g.Kc[a].yd),g.Kc[a]=null)},db:function(a,b){0!==b&&(document.title=b?G(t,b):"");a=a?G(t,a):"";void 0!==g.canvas&&("object"===typeof g.canvas?cb[a]=g.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));g.Bc=H(a);g.Bc||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);g.Bc.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},Sa:function(){window.removeEventListener("beforeunload",
g.gd)},Ra:function(){window.removeEventListener("paste",g.md)},Qa:function(){const a=g.Bc;a.removeEventListener("dragenter",g.hd);a.removeEventListener("dragleave",g.jd);a.removeEventListener("dragover",g.kd);a.removeEventListener("drop",g.ld)},q:function(){g.Bc&&g.Bc.requestPointerLock&&g.Bc.requestPointerLock()},Ya:function(a,b,c){if(g.Bc){if(0===b)a="none";else if(0!=c)a=g.Kc[a].Ad;else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a=
"pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}g.Bc.style.cursor=a}},Va:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),k=e.createImageData(a,b);k.data.set(t.subarray(c,c+a*b*4));e.putImageData(k,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=
d.toDataURL();document.head.appendChild(a)},Za:function(){const a=g.Bc;if(a){let b=void 0;document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement?(document.exitFullscreen?b=document.exitFullscreen():document.webkitExitFullscreen?b=document.webkitExitFullscreen():document.mozCancelFullScreen&&(b=document.mozCancelFullScreen()),b?b.catch(c=>{console.warn("sapp_js_toggle_fullscreen(): failed to exit fullscreen mode with",c);gc(1)}):console.warn("sapp_js_toggle_fullscreen(): browser has no [wekbit|moz]exitFullscreen")):
(a.requestFullscreen?b=a.requestFullscreen():a.webkitRequestFullscreen?b=a.webkitRequestFullscreen():a.mozRequestFullScreen&&(b=a.mozRequestFullScreen()),b?b.catch(c=>{console.warn("sapp_js_toggle_fullscreen(): failed to enter fullscreen mode with",c);gc(0)}):(console.warn("sapp_js_toogle_fullscreen(): browser has no [webkit|moz]requestFullscreen function"),gc(0)))}},ob:function(){return g.Cc?g.Cc.bufferSize:0},qb:function(a,b,c){g.wc=null;g.Cc=null;"undefined"!==typeof AudioContext?g.wc=new AudioContext({sampleRate:a,
latencyHint:"interactive"}):(g.wc=null,console.log("sokol_audio.h: no WebAudio support"));return g.wc?(console.log("sokol_audio.h: sample rate ",g.wc.sampleRate),g.Cc=g.wc.createScriptProcessor(c,0,b),g.Cc.onaudioprocess=d=>{const e=d.outputBuffer.length,k=hc(e);if(k){const f=d.outputBuffer.numberOfChannels;for(let l=0;l<f;l++){const n=d.outputBuffer.getChannelData(l);for(let p=0;p<e;p++)n[p]=x[(k>>2)+(f*p+l)]}}},g.Cc.connect(g.wc.destination),a=()=>{g.wc&&"suspended"===g.wc.state&&g.wc.resume()},
document.addEventListener("click",a,{once:!0}),document.addEventListener("touchend",a,{once:!0}),document.addEventListener("keydown",a,{once:!0}),1):0},pb:function(){return g.wc?g.wc.sampleRate:0},ba:function(){const a=g.wc;null!==a&&(g.Cc&&g.Cc.disconnect(),a.close(),g.wc=null,g.Cc=null)},K:function(a,b,c,d,e,k){const f=b?G(t,b):"";b=new Headers;0<d&&b.append("Range",`bytes=${c}-${c+d-1}`);fetch(f,{method:"GET",headers:b}).then(l=>{l.ok?l.arrayBuffer().then(n=>{n=new Uint8Array(n);n.length<=k?(t.set(n,
e),jc(a,d,n.length)):lc(a)}).catch(n=>{console.error(`sokol_fetch.h: GET ${f} failed with: `,n);mc(a)}):kc(a,l.status)}).catch(l=>{console.error(`sokol_fetch.h: GET ${f} failed with: `,l);mc(a)})},Pa:function(a,b){const c=b?G(t,b):"";fetch(c,{method:"HEAD"}).then(d=>{d.ok?(d=d.headers.get("Content-Length"),null===d?(console.warn(`sokol_fetch.h: HEAD ${c} response has no Content-Length`),mc(a)):ic(a,Number(d))):kc(a,d.status)}).catch(d=>{console.error(`sokol_fetch.h: HEAD ${c} failed with: `,d);mc(a)})},
aa:function(a,b){b=b?G(t,b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}};function pc(a=[]){var b=ac;a.unshift(ea);var c=a.length,d=Ub(4*(c+1)),e=d;a.forEach(f=>{w[e>>2]=Vb(f);e+=4});w[e>>2]=0;try{var k=b(c,d);Ga(k)}catch(f){Ea(f)}}
function qc(a=da){function b(){g.calledRun=!0;if(!q){Z.ac();g.onRuntimeInitialized?.();g.noInitialRun||pc(a);if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var c=g.postRun.shift();za.push(c)}ya(za)}}if(0<z)A=qc;else{if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Ba();ya(Aa);0<z?A=qc:g.setStatus?(g.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>g.setStatus(""),1);b()},1)):b()}}var Z;
(async function(){function a(c){Z=c.exports;oa=Z.$b;c=oa.buffer;r=new Int8Array(c);pa=new Int16Array(c);t=new Uint8Array(c);qa=new Uint16Array(c);v=new Int32Array(c);w=new Uint32Array(c);x=new Float32Array(c);y=new Float64Array(c);ra=new BigInt64Array(c);new BigUint64Array(c);fb=Z.uc;c=Z;g._main=ac=c.bc;g.__sapp_emsc_onpaste=bc=c.cc;g.__sapp_html5_get_ask_leave_site=cc=c.dc;g.__sapp_emsc_begin_drop=dc=c.ec;g.__sapp_emsc_drop=ec=c.fc;g.__sapp_emsc_end_drop=fc=c.gc;g.__sapp_emsc_invoke_fetch_cb=c.hc;
g.__sapp_emsc_set_fullscreen_flag=gc=c.ic;g.__saudio_emsc_pull=hc=c.jc;g.__sfetch_emsc_head_response=ic=c.kc;g.__sfetch_emsc_get_response=jc=c.lc;g.__sfetch_emsc_failed_http_status=kc=c.mc;g.__sfetch_emsc_failed_buffer_too_small=lc=c.nc;g.__sfetch_emsc_failed_other=mc=c.oc;nc=c.pc;M=c.qc;Xb=c.rc;Ub=c.sc;Wb=c.tc;z--;g.monitorRunDependencies?.(z);0==z&&A&&(c=A,A=null,c());return Z}z++;g.monitorRunDependencies?.(z);var b={a:oc};if(g.instantiateWasm)return new Promise(c=>{g.instantiateWasm(b,(d,e)=>{c(a(d,
e))})});ta??=g.locateFile?g.locateFile("demo.wasm",ia):ia+"demo.wasm";return a((await wa(b)).instance)})();qc();
