var g;g||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,ca="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node&&"renderer"!=process.type,da=Object.assign({},g),ea=[],fa="./this.program",ha=(a,b)=>{throw b;},k="",ia,ja;
if(ca){var fs=require("fs");require("path");k=__dirname+"/";ja=a=>{a=ka(a)?new URL(a):a;return fs.readFileSync(a)};ia=async a=>{a=ka(a)?new URL(a):a;return fs.readFileSync(a,void 0)};!g.thisProgram&&1<process.argv.length&&(fa=process.argv[1].replace(/\\/g,"/"));ea=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=g);ha=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba)ba?k=self.location.href:"undefined"!=typeof document&&document.currentScript&&(k=document.currentScript.src),k=k.startsWith("blob:")?
"":k.slice(0,k.replace(/[?#].*/,"").lastIndexOf("/")+1),ba&&(ja=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),ia=async a=>{if(ka(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+
" : "+b.url);};var la=g.print||console.log.bind(console),n=g.printErr||console.error.bind(console);Object.assign(g,da);da=null;g.arguments&&(ea=g.arguments);g.thisProgram&&(fa=g.thisProgram);var ma=g.wasmBinary,na,q=!1,oa,r,t,pa,qa,u,v,x,sa,y,ka=a=>a.startsWith("file://"),ta;
function ua(a,b){function c(){var m=0,p=0;do{var w=f[e++];m+=(w&127)<<p;p+=7}while(w&128);return m}function d(){var m=c();c();0!=(m&1)&&c()}var e=8,h=0;this.qc={};this.tc=[];this.uc={};var f=a;a:for(;e<f.length;){a=f[e++];var l=c()+e;switch(a){case 2:for(a=c();0<a--;)switch(e=c()+e,e=c()+e,f[e++]){case 0:++h;c();break;case 1:c();d();break;case 2:d();break;case 3:e+=2;break;case 4:++e,c()}break;case 10:for(a=c();0<a--;)l=c(),this.qc[h++]=e,this.tc.push(e),e+=l;break a}e=l}b=WebAssembly.Module.customSections(b,
"name");if(b=b.length?b[0]:void 0)for(f=new Uint8Array(b),e=0;e<f.length;)if(b=f[e++],h=c(),1!=b)e+=h;else for(a=c();0<a--;)b=c(),h=c(),this.uc[b]=z(f,e,h),e+=h}var A=0,B=null;function va(a){g.onAbort?.(a);a="Aborted("+a+")";n(a);q=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var wa;
async function xa(a){if(!ma)try{var b=await ia(a);return new Uint8Array(b)}catch{}if(a==wa&&ma)a=new Uint8Array(ma);else if(ja)a=ja(a);else throw"both async and sync fetching of the wasm failed";return a}async function ya(a,b){try{var c=await xa(a),d=await WebAssembly.instantiate(c,b);ta=new ua(c,d.module);return d}catch(e){n(`failed to asynchronously prepare wasm: ${e}`),va(e)}}
async function za(a){var b=wa;if(!ma&&"function"==typeof WebAssembly.instantiateStreaming&&!ka(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"}),d=(await c).clone(),e=await WebAssembly.instantiateStreaming(c,a),h=await d.arrayBuffer();try{ta=new ua(new Uint8Array(h),e.module)}catch(f){n(`failed to initialize offset-converter: ${f}`)}return e}catch(f){n(`wasm streaming compile failed: ${f}`),n("falling back to ArrayBuffer instantiation")}return ya(b,a)}
class Aa{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Ba="undefined"!=typeof TextDecoder?new TextDecoder:void 0,z=(a,b=0,c=NaN)=>{var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Ba)return Ba.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var h=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|h);else{var f=a[b++]&63;e=224==(e&240)?(e&15)<<12|h<<6|f:(e&7)<<18|h<<12|f<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},
Ca=a=>{for(;0<a.length;)a.shift()(g)},Da=[],Ea=[],Fa=()=>{var a=g.preRun.shift();Ea.unshift(a)},Ga=g.noExitRuntime||!0,Ha=0,C={},Ia=a=>{a instanceof Aa||"unwind"==a||ha(1,a)},Ja=a=>{oa=a;Ga||0<Ha||(g.onExit?.(a),q=!0);ha(a,new Aa(a))},Ka=a=>{oa=a;Ja(a)},La=()=>{if(!(Ga||0<Ha))try{var a=oa;oa=a;Ja(a)}catch(b){Ia(b)}},Ma=a=>{if(!q)try{a(),La()}catch(b){Ia(b)}},Ta=(a,b)=>{Na=a;Oa=b;if(D)if(Pa||=!0,0==a)E=function(){setTimeout(G,Math.max(0,Qa+b-performance.now())|0)};else if(1==a)E=function(){Ra(G)};
else if(2==a){if("undefined"==typeof Sa)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Sa=d=>{c.push(d);if(ba){let e;(e=g).setImmediates??(e.setImmediates=[]);g.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}else Sa=setImmediate;E=function(){Sa(G)}}},bb=(a,b,c,d,e)=>{function h(){return f<Ua?(La(),!1):!0}D=a;Va=d;var f=Ua;Pa=
!1;G=function(){if(!q)if(0<Wa.length){var l=Wa.shift();l.sd(l.gd);if(Xa){var m=Xa,p=0==m%1?m-1:Math.floor(m);Xa=l.jd?p:(8*m+(p+.5))/9}g.setStatus&&(l=g.statusMessage||"Please wait...",m=Xa??0,p=Ya.od??0,m?m<p?g.setStatus("{message} ({expected - remaining}/{expected})"):g.setStatus(l):g.setStatus(""));h()&&setTimeout(G,0)}else if(h())if(Za=Za+1|0,1==Na&&1<Oa&&0!=Za%Oa)E();else{0==Na&&(Qa=performance.now());a:if(!q){for(l of $a)if(!1===l())break a;Ma(a);for(m of ab)m()}h()&&E()}};e||(0<b?Ta(0,1E3/b):
Ta(1,1),E());if(c)throw"unwind";},Pa=!1,E=null,Ua=0,D=null,Va=0,Na=0,Oa=0,Za=0,Wa=[],$a=[],ab=[];function cb(){E=null;Ua++}var H=0;function Ra(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===H)H=b+1E3/60;else for(;b+2>=H;)H+=1E3/60;setTimeout(a,Math.max(H-b,0))}}var Ya={},Qa,G,Sa,Xa;function db(a){var b=I.jc[a];b.target.removeEventListener(b.ic,b.Oc,b.kc);I.jc.splice(a,1)}
function eb(){if(navigator.userActivation?navigator.userActivation.isActive:I.Bc&&I.ad.zc){var a=I.pc;I.pc=[];for(var b of a)b.Ec(...b.Kc)}}function J(a){if(!a.target)return-4;if(a.lc)a.Oc=function(c){++I.Bc;I.ad=a;eb();a.mc(c);eb();--I.Bc},a.target.addEventListener(a.ic,a.Oc,a.kc),I.jc.push(a);else for(var b=0;b<I.jc.length;++b)I.jc[b].target==a.target&&I.jc[b].ic==a.ic&&db(b--);return 0}function fb(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var I={hd:0,td:0,Cc:0,yc:0,Ic:0,Gc:0,Ac:0,md:0,yd:0,ld:0,rd:0,Dc:0,Hd:0,Fc:0,vd(a,b,c){r.set(r.subarray(b,b+c),a)},Ad(){for(;I.jc.length;)db(I.jc.length-1);I.pc=[]},Bc:0,pc:[],kd(a,b,c){function d(h,f){if(h.length!=f.length)return!1;for(var l in h)if(h[l]!=f[l])return!1;return!0}for(var e of I.pc)if(e.Ec==a&&d(e.Kc,c))return;I.pc.push({Ec:a,Sc:b,Kc:c});I.pc.sort((h,f)=>h.Sc<f.Sc)},Cd(a){I.pc=I.pc.filter(b=>b.Ec!=a)},jc:[],Bd:(a,b)=>{for(var c=0;c<I.jc.length;++c)I.jc[c].target!=a||b&&b!=I.jc[c].ic||
db(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},gb=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],K=a=>{a=2<a?a?z(t,a):"":a;return gb[a]||("undefined"!=typeof document?document.querySelector(a):null)},hb=a=>0>gb.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},L,M=(a,b,c)=>{var d=t;if(!(0<c))return 0;var e=b;c=b+c-1;for(var h=0;h<a.length;++h){var f=a.charCodeAt(h);if(55296<=f&&57343>=f){var l=a.charCodeAt(++h);
f=65536+((f&1023)<<10)|l&1023}if(127>=f){if(b>=c)break;d[b++]=f}else{if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>6}else{if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&63}d[b++]=128|f>>6&63}d[b++]=128|f&63}}d[b]=0;return b-e},ib=(a,b,c,d,e,h)=>{I.Ac||(I.Ac=N(256));a={target:K(a),ic:h,lc:d,mc:(f=event)=>{var l=f.target.id?f.target.id:"",m=I.Ac;M(fb(f.target),m+0,128);M(l,m+128,128);L.get(d)(e,m,b)&&f.preventDefault()},kc:c};return J(a)},jb=(a,b,c,
d,e,h)=>{I.Cc||(I.Cc=N(160));a={target:K(a),ic:h,lc:d,mc:f=>{var l=I.Cc;y[l>>3]=f.timeStamp;var m=l>>2;u[m+2]=f.location;r[l+12]=f.ctrlKey;r[l+13]=f.shiftKey;r[l+14]=f.altKey;r[l+15]=f.metaKey;r[l+16]=f.repeat;u[m+5]=f.charCode;u[m+6]=f.keyCode;u[m+7]=f.which;M(f.key||"",l+32,32);M(f.code||"",l+64,32);M(f.char||"",l+96,32);M(f.locale||"",l+128,32);L.get(d)(e,l,b)&&f.preventDefault()},kc:c};return J(a)},kb=(a,b,c)=>{y[a>>3]=b.timeStamp;var d=a>>2;u[d+2]=b.screenX;u[d+3]=b.screenY;u[d+4]=b.clientX;
u[d+5]=b.clientY;r[a+24]=b.ctrlKey;r[a+25]=b.shiftKey;r[a+26]=b.altKey;r[a+27]=b.metaKey;pa[2*d+14]=b.button;pa[2*d+15]=b.buttons;u[d+8]=b.movementX;u[d+9]=b.movementY;a=hb(c);u[d+10]=b.clientX-(a.left|0);u[d+11]=b.clientY-(a.top|0)},O=(a,b,c,d,e,h)=>{I.yc||(I.yc=N(64));a=K(a);return J({target:a,zc:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,ic:h,lc:d,mc:(f=event)=>{kb(I.yc,f,a);L.get(d)(e,I.yc,b)&&f.preventDefault()},kc:c})},lb=(a,b,c,d,e)=>{I.Dc||(I.Dc=N(257));return J({target:a,ic:e,lc:d,
mc:(h=event)=>{var f=I.Dc,l=document.pointerLockElement||document.qc||document.uc||document.tc;r[f]=!!l;var m=l?.id||"";M(fb(l),f+1,128);M(m,f+129,128);L.get(d)(20,f,b)&&h.preventDefault()},kc:c})},mb=(a,b,c,d,e)=>J({target:a,ic:e,lc:d,mc:(h=event)=>{L.get(d)(38,0,b)&&h.preventDefault()},kc:c}),nb=(a,b,c,d)=>{I.Gc||(I.Gc=N(36));a=K(a);return J({target:a,ic:"resize",lc:d,mc:(e=event)=>{if(e.target==a){var h=document.body;if(h){var f=I.Gc;u[f>>2]=0;u[f+4>>2]=h.clientWidth;u[f+8>>2]=h.clientHeight;u[f+
12>>2]=innerWidth;u[f+16>>2]=innerHeight;u[f+20>>2]=outerWidth;u[f+24>>2]=outerHeight;u[f+28>>2]=pageXOffset|0;u[f+32>>2]=pageYOffset|0;L.get(d)(10,f,b)&&e.preventDefault()}}},kc:c})},ob=(a,b,c,d,e,h)=>{I.Fc||(I.Fc=N(1552));a=K(a);return J({target:a,zc:"touchstart"==h||"touchend"==h,ic:h,lc:d,mc:f=>{var l={},m=f.touches;for(var p of m)p.Pc=p.Rc=0,l[p.identifier]=p;for(var w of f.changedTouches)w.Pc=1,l[w.identifier]=w;for(var ra of f.targetTouches)l[ra.identifier].Rc=1;m=I.Fc;y[m>>3]=f.timeStamp;
r[m+12]=f.ctrlKey;r[m+13]=f.shiftKey;r[m+14]=f.altKey;r[m+15]=f.metaKey;p=m+16;w=hb(a);ra=0;for(let F of Object.values(l))if(l=p>>2,u[l]=F.identifier,u[l+1]=F.screenX,u[l+2]=F.screenY,u[l+3]=F.clientX,u[l+4]=F.clientY,u[l+5]=F.pageX,u[l+6]=F.pageY,r[p+28]=F.Pc,r[p+29]=F.Rc,u[l+8]=F.clientX-(w.left|0),u[l+9]=F.clientY-(w.top|0),p+=48,31<++ra)break;u[m+8>>2]=ra;L.get(d)(e,m,b)&&f.preventDefault()},kc:c})},P,pb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,
d),a.drawArraysInstanced=(c,d,e,h)=>b.drawArraysInstancedANGLE(c,d,e,h),a.drawElementsInstanced=(c,d,e,h,f)=>b.drawElementsInstancedANGLE(c,d,e,h,f))},qb=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},rb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},sb=a=>
{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},tb=1,Q=[],R=[],ub=[],vb=[],wb=[],S=[],xb=[],yb=[],T=[],zb={},Ab=4,Bb=0,Cb=a=>{for(var b=tb++,c=a.length;c<b;c++)a[c]=null;return b},Db=(a,b,c,d)=>{for(var e=0;e<a;e++){var h=P[c](),f=h&&Cb(d);h?(h.name=f,d[f]=h):U||=1282;u[b+4*e>>2]=f}},Fb=(a,b)=>{a.qc||(a.qc=a.getContext,a.getContext=function(d,e){e=a.qc(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.Qc?a.getContext("webgl2",b):a.getContext("webgl",b);
return c?Eb(c,b):0},Eb=(a,b)=>{var c=Cb(yb),d={handle:c,attributes:b,version:b.Qc,Jc:a};a.canvas&&(a.canvas.ed=d);yb[c]=d;("undefined"==typeof b.Nc||b.Nc)&&Gb(d);return c},Gb=a=>{a||=V;if(!a.dd){a.dd=!0;var b=a.Jc;b.xd=b.getExtension("WEBGL_multi_draw");b.qd=b.getExtension("EXT_polygon_offset_clamp");b.pd=b.getExtension("EXT_clip_control");b.Id=b.getExtension("WEBGL_polygon_mode");pb(b);qb(b);rb(b);b.nd=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.ud=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");
2<=a.version&&(b.Mc=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.Mc)b.Mc=b.getExtension("EXT_disjoint_timer_query");sb(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},U,V,Hb=(a,b,c,d,e,h)=>{a={target:K(a),ic:h,lc:d,mc:(f=event)=>{L.get(d)(e,0,b)&&f.preventDefault()},kc:c};J(a)},Ib=(a,b,c,d)=>{I.Ic||(I.Ic=N(96));return J({target:a,zc:!0,ic:"wheel",lc:d,mc:(e=event)=>{var h=I.Ic;kb(h,e,a);y[h+64>>3]=e.deltaX;y[h+72>>3]=e.deltaY;y[h+80>>
3]=e.deltaZ;u[h+88>>2]=e.deltaMode;L.get(d)(9,h,b)&&e.preventDefault()},kc:c})},Jb=["default","low-power","high-performance"],Kb=[null,[],[]],Lb=()=>{var a=sb(P);return a=a.concat(a.map(b=>"GL_"+b))},Mb=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=P.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>V.version){U||=1282;return}c=Lb().length;break;case 33307:case 33308:if(2>V.version){U||=1280;return}c=33307==a?3:
0}if(void 0===c)switch(d=P.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":U||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=0;break;default:U||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||
d instanceof Array){for(a=0;a<d.length;++a)u[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){U||=1280;n(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:U||=1280;n(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}u[b>>2]=c}else U||=1281},Nb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},
Ob=a=>{var b=Nb(a)+1,c=N(b);c&&M(a,c,b);return c},Pb=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Qb=[],Rb=a=>{a-=5120;return 0==a?r:1==a?t:2==a?pa:4==a?u:6==a?x:5==a||28922==a||28520==a||30779==a||30782==a?v:qa},W=a=>{var b=P.bd;if(b){var c=b.sc[a];"number"==typeof c&&(b.sc[a]=c=P.getUniformLocation(b,b.Zc[a]+(0<c?`[${c}]`:"")));return c}U||=1282},X=[],Sb=[],Ub=a=>{var b=Nb(a)+1,c=Tb(b);M(a,c,b);return c},Xb=a=>{var b=Vb();a();Wb(b)};g.requestAnimationFrame=Ra;g.pauseMainLoop=cb;
g.resumeMainLoop=function(){Ua++;var a=Na,b=Oa,c=D;D=null;bb(c,0,!1,Va,!0);Ta(a,b);E()};g.preMainLoop&&$a.push(g.preMainLoop);g.postMainLoop&&ab.push(g.postMainLoop);for(var Y=0;32>Y;++Y)Qb.push(Array(Y));var Yb=new Float32Array(288);for(Y=0;288>=Y;++Y)X[Y]=Yb.subarray(0,Y);var Zb=new Int32Array(288);for(Y=0;288>=Y;++Y)Sb[Y]=Zb.subarray(0,Y);
var lc={Pa:()=>va(""),eb:()=>{Ga=!1;Ha=0},fb:(a,b)=>{C[a]&&(clearTimeout(C[a].id),delete C[a]);if(!b)return 0;var c=setTimeout(()=>{delete C[a];Ma(()=>$b(a,performance.now()))},b);C[a]={id:c,Gd:b};return 0},gb:function(a,b,c){if(!(0<=a&&3>=a))return 28;sa[c>>3]=BigInt(Math.round(1E6*(0===a?Date.now():performance.now())));return 0},Va:()=>{cb();D=null},K:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,ha:(a,b,c)=>{a=K(a);if(!a)return-4;a=hb(a);y[b>>3]=a.width;y[c>>3]=a.height;return 0},
Wa:()=>performance.now(),_a:(a,b)=>{function c(d){L.get(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},Ra:()=>{va("OOM")},g:a=>{var b=Error().stack.toString().split("\n");"Error"==b[0]&&b.shift();a=b[a+3];var c;return(c=/\bwasm-function\[\d+\]:(0x[0-9a-f]+)/.exec(a))?+c[1]:(c=/\bwasm-function\[(\d+)\]:(\d+)/.exec(a))?ta.qc[+c[1]]+ +c[2]:(c=/:(\d+):\d+(?:\)|$)/.exec(a))?2147483648|+c[1]:0},N:(a,b,c,d)=>ib(a,b,c,d,12,"blur"),J:(a,b,c)=>{a=K(a);if(!a)return-4;a.width=b;a.height=c;
return 0},O:(a,b,c,d)=>ib(a,b,c,d,13,"focus"),Z:(a,b,c,d)=>jb(a,b,c,d,2,"keydown"),W:(a,b,c,d)=>jb(a,b,c,d,1,"keypress"),X:(a,b,c,d)=>jb(a,b,c,d,3,"keyup"),$a:(a,b,c)=>{a=L.get(a);bb(a,b,c)},C:(a,b,c,d)=>O(a,b,c,d,5,"mousedown"),ba:(a,b,c,d)=>O(a,b,c,d,33,"mouseenter"),aa:(a,b,c,d)=>O(a,b,c,d,34,"mouseleave"),ga:(a,b,c,d)=>O(a,b,c,d,8,"mousemove"),y:(a,b,c,d)=>O(a,b,c,d,6,"mouseup"),Q:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.qc||document.body.uc||
document.body.tc))return-1;a=K(a);if(!a)return-4;lb(a,b,c,d,"mozpointerlockchange");lb(a,b,c,d,"webkitpointerlockchange");lb(a,b,c,d,"mspointerlockchange");return lb(a,b,c,d,"pointerlockchange")},P:(a,b,c,d)=>{if(!document||!(document.body.requestPointerLock||document.body.qc||document.body.uc||document.body.tc))return-1;a=K(a);if(!a)return-4;mb(a,b,c,d,"mozpointerlockerror");mb(a,b,c,d,"webkitpointerlockerror");mb(a,b,c,d,"mspointerlockerror");return mb(a,b,c,d,"pointerlockerror")},S:(a,b,c,d)=>
nb(a,b,c,d),R:(a,b,c,d)=>ob(a,b,c,d,25,"touchcancel"),T:(a,b,c,d)=>ob(a,b,c,d,23,"touchend"),U:(a,b,c,d)=>ob(a,b,c,d,24,"touchmove"),V:(a,b,c,d)=>ob(a,b,c,d,22,"touchstart"),M:(a,b,c,d)=>{Hb(a,b,c,d,31,"webglcontextlost");return 0},L:(a,b,c,d)=>{Hb(a,b,c,d,32,"webglcontextrestored");return 0},$:(a,b,c,d)=>(a=K(a))?"undefined"!=typeof a.onwheel?Ib(a,b,c,d):-1:-4,Ja:(a,b)=>{var c=b>>2;b={alpha:!!r[b+0],depth:!!r[b+1],stencil:!!r[b+2],antialias:!!r[b+3],premultipliedAlpha:!!r[b+4],preserveDrawingBuffer:!!r[b+
5],powerPreference:Jb[u[c+2]],failIfMajorPerformanceCaveat:!!r[b+12],Qc:u[c+4],wd:u[c+5],Nc:r[b+24],cd:r[b+25],zd:u[c+7],Dd:r[b+32]};a=K(a);return!a||b.cd?0:Fb(a,b)},Ca:a=>{V=yb[a];g.ctx=P=V?.Jc;return!a||P?0:-5},Qa:(a,b,c,d)=>{for(var e=0,h=0;h<c;h++){var f=v[b>>2],l=v[b+4>>2];b+=8;for(var m=0;m<l;m++){var p=t[f+m],w=Kb[a];0===p||10===p?((1===a?la:n)(z(w)),w.length=0):w.push(p)}e+=l}v[d>>2]=e;return 0},s:a=>P.activeTexture(a),p:(a,b)=>{P.attachShader(R[a],S[b])},b:(a,b)=>{35051==a?P.Lc=b:35052==
a&&(P.rc=b);P.bindBuffer(a,Q[b])},t:(a,b,c)=>{P.bindBufferBase(a,b,Q[c])},j:(a,b)=>{P.bindFramebuffer(a,ub[b])},Aa:(a,b)=>{P.bindRenderbuffer(a,vb[b])},r:(a,b)=>{P.bindSampler(a,T[b])},f:(a,b)=>{P.bindTexture(a,wb[b])},I:a=>{P.bindVertexArray(xb[a])},fa:(a,b,c,d)=>P.blendColor(a,b,c,d),u:(a,b)=>P.blendEquationSeparate(a,b),v:(a,b,c,d)=>P.blendFuncSeparate(a,b,c,d),tb:(a,b,c,d,e,h,f,l,m,p)=>P.blitFramebuffer(a,b,c,d,e,h,f,l,m,p),Da:(a,b,c,d)=>{2<=V.version?c&&b?P.bufferData(a,t,d,c,b):P.bufferData(a,
b,d):P.bufferData(a,c?t.subarray(c,c+b):b,d)},G:(a,b,c,d)=>{2<=V.version?c&&P.bufferSubData(a,b,t,d,c):P.bufferSubData(a,b,t.subarray(d,d+c))},la:(a,b,c,d)=>P.clearBufferfi(a,b,c,d),x:(a,b,c)=>{P.clearBufferfv(a,b,x,c>>2)},ka:(a,b,c)=>{P.clearBufferiv(a,b,u,c>>2)},i:(a,b,c,d)=>{P.colorMask(!!a,!!b,!!c,!!d)},mb:a=>{P.compileShader(S[a])},ta:(a,b,c,d,e,h,f,l)=>{2<=V.version?P.rc||!f?P.compressedTexImage2D(a,b,c,d,e,h,f,l):P.compressedTexImage2D(a,b,c,d,e,h,t,l,f):P.compressedTexImage2D(a,b,c,d,e,h,
t.subarray(l,l+f))},va:(a,b,c,d,e,h,f,l,m)=>{P.rc?P.compressedTexImage3D(a,b,c,d,e,h,f,l,m):P.compressedTexImage3D(a,b,c,d,e,h,f,t,m,l)},pa:()=>{var a=Cb(R),b=P.createProgram();b.name=a;b.xc=b.vc=b.wc=0;b.Hc=1;R[a]=b;return a},ob:a=>{var b=Cb(S);S[b]=P.createShader(a);return b},ea:a=>P.cullFace(a),pb:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=Q[d];e&&(P.deleteBuffer(e),e.name=0,Q[d]=null,d==P.Lc&&(P.Lc=0),d==P.rc&&(P.rc=0))}},H:(a,b)=>{for(var c=0;c<a;++c){var d=u[b+4*c>>2],e=ub[d];e&&(P.deleteFramebuffer(e),
e.name=0,ub[d]=null)}},k:a=>{if(a){var b=R[a];b?(P.deleteProgram(b),b.name=0,R[a]=null):U||=1281}},Ha:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=vb[d];e&&(P.deleteRenderbuffer(e),e.name=0,vb[d]=null)}},Ga:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=T[d];e&&(P.deleteSampler(e),e.name=0,T[d]=null)}},h:a=>{if(a){var b=S[a];b?(P.deleteShader(b),S[a]=null):U||=1281}},Ia:(a,b)=>{for(var c=0;c<a;c++){var d=u[b+4*c>>2],e=wb[d];e&&(P.deleteTexture(e),e.name=0,wb[d]=null)}},Fa:(a,b)=>{for(var c=
0;c<a;c++){var d=u[b+4*c>>2];P.deleteVertexArray(xb[d]);xb[d]=null}},n:a=>P.depthFunc(a),o:a=>{P.depthMask(!!a)},c:a=>P.disable(a),ca:a=>{P.disableVertexAttribArray(a)},vb:(a,b,c)=>{P.drawArrays(a,b,c)},wb:(a,b,c,d)=>{P.drawArraysInstanced(a,b,c,d)},yb:(a,b,c,d)=>{P.drawElements(a,b,c,d)},xb:(a,b,c,d,e)=>{P.drawElementsInstanced(a,b,c,d,e)},e:a=>P.enable(a),Ib:a=>{P.enableVertexAttribArray(a)},da:a=>P.frontFace(a),Ea:(a,b)=>{Db(a,b,"createBuffer",Q)},Ba:(a,b)=>{Db(a,b,"createRenderbuffer",vb)},qa:(a,
b)=>{Db(a,b,"createSampler",T)},ya:(a,b)=>{Db(a,b,"createTexture",wb)},La:(a,b)=>{Db(a,b,"createVertexArray",xb)},ma:(a,b)=>P.getAttribLocation(R[a],b?z(t,b):""),a:(a,b)=>Mb(a,b),oa:(a,b,c,d)=>{a=P.getProgramInfoLog(R[a]);null===a&&(a="(unknown error)");b=0<b&&d?M(a,d,b):0;c&&(u[c>>2]=b)},D:(a,b,c)=>{if(c)if(a>=tb)U||=1281;else if(a=R[a],35716==b)a=P.getProgramInfoLog(a),null===a&&(a="(unknown error)"),u[c>>2]=a.length+1;else if(35719==b){if(!a.xc){var d=P.getProgramParameter(a,35718);for(b=0;b<d;++b)a.xc=
Math.max(a.xc,P.getActiveUniform(a,b).name.length+1)}u[c>>2]=a.xc}else if(35722==b){if(!a.vc)for(d=P.getProgramParameter(a,35721),b=0;b<d;++b)a.vc=Math.max(a.vc,P.getActiveAttrib(a,b).name.length+1);u[c>>2]=a.vc}else if(35381==b){if(!a.wc)for(d=P.getProgramParameter(a,35382),b=0;b<d;++b)a.wc=Math.max(a.wc,P.getActiveUniformBlockName(a,b).length+1);u[c>>2]=a.wc}else u[c>>2]=P.getProgramParameter(a,b);else U||=1281},lb:(a,b,c,d)=>{a=P.getShaderInfoLog(S[a]);null===a&&(a="(unknown error)");b=0<b&&d?
M(a,d,b):0;c&&(u[c>>2]=b)},_:(a,b,c)=>{c?35716==b?(a=P.getShaderInfoLog(S[a]),null===a&&(a="(unknown error)"),u[c>>2]=a?a.length+1:0):35720==b?(a=P.getShaderSource(S[a]),u[c>>2]=a?a.length+1:0):u[c>>2]=P.getShaderParameter(S[a],b):U||=1281},Ma:(a,b)=>{if(2>V.version)return U||=1282,0;var c=zb[a];if(c)return 0>b||b>=c.length?(U||=1281,0):c[b];switch(a){case 7939:return c=Lb().map(Ob),c=zb[a]=c,0>b||b>=c.length?(U||=1281,0):c[b];default:return U||=1280,0}},B:(a,b)=>{b=b?z(t,b):"";if(a=R[a]){var c=a,
d=c.sc,e=c.$c,h;if(!d){c.sc=d={};c.Zc={};var f=P.getProgramParameter(c,35718);for(h=0;h<f;++h){var l=P.getActiveUniform(c,h);var m=l.name;l=l.size;var p=Pb(m);p=0<p?m.slice(0,p):m;var w=c.Hc;c.Hc+=l;e[p]=[l,w];for(m=0;m<l;++m)d[w]=m,c.Zc[w++]=p}}c=a.sc;d=0;e=b;h=Pb(b);0<h&&(d=parseInt(b.slice(h+1))>>>0,e=b.slice(0,h));if((e=a.$c[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||P.getUniformLocation(a,b)))return d}else U||=1281;return-1},sb:(a,b,c)=>{for(var d=Qb[b],e=0;e<b;e++)d[e]=u[c+4*e>>2];P.invalidateFramebuffer(a,
d)},E:a=>{a=R[a];P.linkProgram(a);a.sc=0;a.$c={}},Ka:(a,b)=>{3317==a?Ab=b:3314==a&&(Bb=b);P.pixelStorei(a,b)},w:(a,b)=>P.polygonOffset(a,b),ub:a=>P.readBuffer(a),za:(a,b,c,d,e)=>P.renderbufferStorageMultisample(a,b,c,d,e),F:(a,b,c)=>{P.samplerParameterf(T[a],b,c)},d:(a,b,c)=>{P.samplerParameteri(T[a],b,c)},z:(a,b,c,d)=>P.scissor(a,b,c,d),nb:(a,b,c,d)=>{for(var e="",h=0;h<b;++h){var f=(f=v[c+4*h>>2])?z(t,f,d?v[d+4*h>>2]:void 0):"";e+=f}P.shaderSource(S[a],e)},rb:(a,b,c)=>P.stencilFunc(a,b,c),ja:(a,
b,c,d)=>P.stencilFuncSeparate(a,b,c,d),m:a=>P.stencilMask(a),qb:(a,b,c)=>P.stencilOp(a,b,c),ia:(a,b,c,d)=>P.stencilOpSeparate(a,b,c,d),sa:(a,b,c,d,e,h,f,l,m)=>{if(2<=V.version){if(P.rc){P.texImage2D(a,b,c,d,e,h,f,l,m);return}if(m){var p=Rb(l);m>>>=31-Math.clz32(p.BYTES_PER_ELEMENT);P.texImage2D(a,b,c,d,e,h,f,l,p,m);return}}if(m){p=Rb(l);var w=e*((Bb||d)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[f-6402]||1)*p.BYTES_PER_ELEMENT+Ab-1&-Ab);m=p.subarray(m>>>31-Math.clz32(p.BYTES_PER_ELEMENT),
m+w>>>31-Math.clz32(p.BYTES_PER_ELEMENT))}else m=null;P.texImage2D(a,b,c,d,e,h,f,l,m)},ua:(a,b,c,d,e,h,f,l,m,p)=>{if(P.rc)P.texImage3D(a,b,c,d,e,h,f,l,m,p);else if(p){var w=Rb(m);P.texImage3D(a,b,c,d,e,h,f,l,m,w,p>>>31-Math.clz32(w.BYTES_PER_ELEMENT))}else P.texImage3D(a,b,c,d,e,h,f,l,m,null)},xa:(a,b,c)=>P.texParameteri(a,b,c),ra:(a,b,c,d,e)=>P.texStorage2D(a,b,c,d,e),wa:(a,b,c,d,e,h)=>P.texStorage3D(a,b,c,d,e,h),Hb:(a,b,c)=>{if(2<=V.version)b&&P.uniform1fv(W(a),x,c>>2,b);else{if(288>=b)for(var d=
X[b],e=0;e<b;++e)d[e]=x[c+4*e>>2];else d=x.subarray(c>>2,c+4*b>>2);P.uniform1fv(W(a),d)}},na:(a,b)=>{P.uniform1i(W(a),b)},Db:(a,b,c)=>{if(2<=V.version)b&&P.uniform1iv(W(a),u,c>>2,b);else{if(288>=b)for(var d=Sb[b],e=0;e<b;++e)d[e]=u[c+4*e>>2];else d=u.subarray(c>>2,c+4*b>>2);P.uniform1iv(W(a),d)}},Gb:(a,b,c)=>{if(2<=V.version)b&&P.uniform2fv(W(a),x,c>>2,2*b);else{if(144>=b){b*=2;for(var d=X[b],e=0;e<b;e+=2)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2]}else d=x.subarray(c>>2,c+8*b>>2);P.uniform2fv(W(a),d)}},
Cb:(a,b,c)=>{if(2<=V.version)b&&P.uniform2iv(W(a),u,c>>2,2*b);else{if(144>=b){b*=2;for(var d=Sb[b],e=0;e<b;e+=2)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2]}else d=u.subarray(c>>2,c+8*b>>2);P.uniform2iv(W(a),d)}},Fb:(a,b,c)=>{if(2<=V.version)b&&P.uniform3fv(W(a),x,c>>2,3*b);else{if(96>=b){b*=3;for(var d=X[b],e=0;e<b;e+=3)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2]}else d=x.subarray(c>>2,c+12*b>>2);P.uniform3fv(W(a),d)}},Bb:(a,b,c)=>{if(2<=V.version)b&&P.uniform3iv(W(a),u,c>>2,3*b);else{if(96>=
b){b*=3;for(var d=Sb[b],e=0;e<b;e+=3)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2]}else d=u.subarray(c>>2,c+12*b>>2);P.uniform3iv(W(a),d)}},Eb:(a,b,c)=>{if(2<=V.version)b&&P.uniform4fv(W(a),x,c>>2,4*b);else{if(72>=b){var d=X[4*b],e=x;c>>=2;b*=4;for(var h=0;h<b;h+=4){var f=c+h;d[h]=e[f];d[h+1]=e[f+1];d[h+2]=e[f+2];d[h+3]=e[f+3]}}else d=x.subarray(c>>2,c+16*b>>2);P.uniform4fv(W(a),d)}},Ab:(a,b,c)=>{if(2<=V.version)b&&P.uniform4iv(W(a),u,c>>2,4*b);else{if(72>=b){b*=4;for(var d=Sb[b],
e=0;e<b;e+=4)d[e]=u[c+4*e>>2],d[e+1]=u[c+(4*e+4)>>2],d[e+2]=u[c+(4*e+8)>>2],d[e+3]=u[c+(4*e+12)>>2]}else d=u.subarray(c>>2,c+16*b>>2);P.uniform4iv(W(a),d)}},zb:(a,b,c,d)=>{if(2<=V.version)b&&P.uniformMatrix4fv(W(a),!!c,x,d>>2,16*b);else{if(18>=b){var e=X[16*b],h=x;d>>=2;b*=16;for(var f=0;f<b;f+=16){var l=d+f;e[f]=h[l];e[f+1]=h[l+1];e[f+2]=h[l+2];e[f+3]=h[l+3];e[f+4]=h[l+4];e[f+5]=h[l+5];e[f+6]=h[l+6];e[f+7]=h[l+7];e[f+8]=h[l+8];e[f+9]=h[l+9];e[f+10]=h[l+10];e[f+11]=h[l+11];e[f+12]=h[l+12];e[f+13]=
h[l+13];e[f+14]=h[l+14];e[f+15]=h[l+15]}}else e=x.subarray(d>>2,d+64*b>>2);P.uniformMatrix4fv(W(a),!!c,e)}},l:a=>{a=R[a];P.useProgram(a);P.bd=a},Jb:(a,b)=>{P.vertexAttribDivisor(a,b)},Kb:(a,b,c,d,e)=>{P.vertexAttribIPointer(a,b,c,d,e)},Lb:(a,b,c,d,e,h)=>{P.vertexAttribPointer(a,b,c,!!d,e,h)},A:(a,b,c,d)=>P.viewport(a,b,c,d),db:Ja,cb:function(){g.Tc=a=>{0!=ac()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",g.Tc)},bb:function(){g.Yc=a=>{const b=a.clipboardData.getData("text");
Xb(()=>{const c=Ub(b);bc(c)})};window.addEventListener("paste",g.Yc)},ab:function(){g.Ed=[];g.Uc=b=>{b.stopPropagation();b.preventDefault()};g.Vc=b=>{b.stopPropagation();b.preventDefault()};g.Wc=b=>{b.stopPropagation();b.preventDefault()};g.Xc=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;g.Fd=c;cc(c.length);for(let e=0;e<c.length;e++)Xb(()=>{const h=Ub(c[e].name);dc(e,h)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);ec(b.clientX,b.clientY,
d)};const a=g.nc;a.addEventListener("dragenter",g.Uc,!1);a.addEventListener("dragleave",g.Vc,!1);a.addEventListener("dragover",g.Wc,!1);a.addEventListener("drop",g.Xc,!1)},Ya:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},Mb:function(a,b){0!==b&&(document.title=b?z(t,b):"");a=a?z(t,a):"";void 0!==g.canvas&&("object"===typeof g.canvas?gb[a]=g.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));g.nc=K(a);g.nc||console.warn("sokol_app.h: can't find html5_canvas_selector ",
a);g.nc.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},Ua:function(){window.removeEventListener("beforeunload",g.Tc)},Ta:function(){window.removeEventListener("paste",g.Yc)},Sa:function(){const a=g.nc;a.removeEventListener("dragenter",g.Uc);a.removeEventListener("dragleave",g.Vc);a.removeEventListener("dragover",g.Wc);a.removeEventListener("drop",g.Xc)},q:function(){g.nc&&g.nc.requestPointerLock&&g.nc.requestPointerLock()},Za:function(a,b){if(g.nc){if(0===
b)a="none";else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a="not-allowed";break;default:a="auto"}g.nc.style.cursor=a}},Xa:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),h=e.createImageData(a,b);h.data.set(t.subarray(c,
c+a*b*4));e.putImageData(h,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},ib:function(){return g.oc?g.oc.bufferSize:0},kb:function(a,b,c){g.hc=null;g.oc=null;"undefined"!==typeof AudioContext?g.hc=new AudioContext({sampleRate:a,latencyHint:"interactive"}):(g.hc=null,console.log("sokol_audio.h: no WebAudio support"));return g.hc?(console.log("sokol_audio.h: sample rate ",g.hc.sampleRate),g.oc=g.hc.createScriptProcessor(c,
0,b),g.oc.onaudioprocess=d=>{const e=d.outputBuffer.length,h=fc(e);if(h){const f=d.outputBuffer.numberOfChannels;for(let l=0;l<f;l++){const m=d.outputBuffer.getChannelData(l);for(let p=0;p<e;p++)m[p]=x[(h>>2)+(f*p+l)]}}},g.oc.connect(g.hc.destination),a=()=>{g.hc&&"suspended"===g.hc.state&&g.hc.resume()},document.addEventListener("click",a,{once:!0}),document.addEventListener("touchend",a,{once:!0}),document.addEventListener("keydown",a,{once:!0}),1):0},jb:function(){return g.hc?g.hc.sampleRate:0},
hb:function(){const a=g.hc;null!==a&&(g.oc&&g.oc.disconnect(),a.close(),g.hc=null,g.oc=null)},Oa:function(a,b,c,d,e,h){const f=b?z(t,b):"";b=new Headers;0<d&&b.append("Range",`bytes=${c}-${c+d-1}`);fetch(f,{method:"GET",headers:b}).then(l=>{l.ok?l.arrayBuffer().then(m=>{m=new Uint8Array(m);m.length<=h?(t.set(m,e),gc(a,d,m.length)):hc(a)}).catch(m=>{console.error(`sokol_fetch.h: GET ${f} failed with: `,m);ic(a)}):jc(a,l.status)}).catch(l=>{console.error(`sokol_fetch.h: GET ${f} failed with: `,l);ic(a)})},
Na:function(a,b){const c=b?z(t,b):"";fetch(c,{method:"HEAD"}).then(d=>{d.ok?(d=d.headers.get("Content-Length"),null===d?(console.warn(`sokol_fetch.h: HEAD ${c} response has no Content-Length`),ic(a)):kc(a,Number(d))):jc(a,d.status)}).catch(d=>{console.error(`sokol_fetch.h: HEAD ${c} failed with: `,d);ic(a)})},Y:function(a,b){b=b?z(t,b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}},Z;
(async function(){function a(c){Z=c.exports;na=Z.Nb;c=na.buffer;g.HEAP8=r=new Int8Array(c);g.HEAP16=pa=new Int16Array(c);g.HEAPU8=t=new Uint8Array(c);g.HEAPU16=qa=new Uint16Array(c);g.HEAP32=u=new Int32Array(c);g.HEAPU32=v=new Uint32Array(c);g.HEAPF32=x=new Float32Array(c);g.HEAPF64=y=new Float64Array(c);g.HEAP64=sa=new BigInt64Array(c);g.HEAPU64=new BigUint64Array(c);L=Z.fc;A--;g.monitorRunDependencies?.(A);0==A&&B&&(c=B,B=null,c());return Z}A++;g.monitorRunDependencies?.(A);var b={a:lc};if(g.instantiateWasm)return new Promise(c=>
{g.instantiateWasm(b,(d,e)=>{a(d,e);c(d.exports)})});wa??=g.locateFile?g.locateFile("demo.wasm",k):k+"demo.wasm";return a((await za(b)).instance)})();
var mc=g._main=(a,b)=>(mc=g._main=Z.Pb)(a,b),bc=g.__sapp_emsc_onpaste=a=>(bc=g.__sapp_emsc_onpaste=Z.Qb)(a),ac=g.__sapp_html5_get_ask_leave_site=()=>(ac=g.__sapp_html5_get_ask_leave_site=Z.Rb)(),cc=g.__sapp_emsc_begin_drop=a=>(cc=g.__sapp_emsc_begin_drop=Z.Sb)(a),dc=g.__sapp_emsc_drop=(a,b)=>(dc=g.__sapp_emsc_drop=Z.Tb)(a,b),ec=g.__sapp_emsc_end_drop=(a,b,c)=>(ec=g.__sapp_emsc_end_drop=Z.Ub)(a,b,c);
g.__sapp_emsc_invoke_fetch_cb=(a,b,c,d,e,h,f,l)=>(g.__sapp_emsc_invoke_fetch_cb=Z.Vb)(a,b,c,d,e,h,f,l);
var fc=g.__saudio_emsc_pull=a=>(fc=g.__saudio_emsc_pull=Z.Wb)(a),kc=g.__sfetch_emsc_head_response=(a,b)=>(kc=g.__sfetch_emsc_head_response=Z.Xb)(a,b),gc=g.__sfetch_emsc_get_response=(a,b,c)=>(gc=g.__sfetch_emsc_get_response=Z.Yb)(a,b,c),jc=g.__sfetch_emsc_failed_http_status=(a,b)=>(jc=g.__sfetch_emsc_failed_http_status=Z.Zb)(a,b),hc=g.__sfetch_emsc_failed_buffer_too_small=a=>(hc=g.__sfetch_emsc_failed_buffer_too_small=Z._b)(a),ic=g.__sfetch_emsc_failed_other=a=>(ic=g.__sfetch_emsc_failed_other=Z.$b)(a),
$b=(a,b)=>($b=Z.ac)(a,b),N=a=>(N=Z.bc)(a),Wb=a=>(Wb=Z.cc)(a),Tb=a=>(Tb=Z.dc)(a),Vb=()=>(Vb=Z.ec)();function nc(a=[]){var b=mc;a.unshift(fa);var c=a.length,d=Tb(4*(c+1)),e=d;a.forEach(f=>{v[e>>2]=Ub(f);e+=4});v[e>>2]=0;try{var h=b(c,d);Ka(h)}catch(f){Ia(f)}}
function oc(a=ea){function b(){g.calledRun=!0;if(!q){Z.Ob();g.onRuntimeInitialized?.();g.noInitialRun||nc(a);if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var c=g.postRun.shift();Da.unshift(c)}Ca(Da)}}if(0<A)B=oc;else{if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Fa();Ca(Ea);0<A?B=oc:g.setStatus?(g.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>g.setStatus(""),1);b()},1)):b()}}
if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();oc();
